### ISSUE TITLE
Moving just the contents up from directory

### ISSUE THREAD

**Issue by edwardessing** [mattwidmann/metalsmith-copy#14]
I was wondering if there is a way that I can move just the contents one (or more) levels up from a directory. 
For example:
`| main folder`
`| – – 1.jpg`
`| – – subfolder`
`| – – | – – 2.jpg`

In this instance I would like to move `2.jpg` into the main folder so it would become:
`| main folder`
`| – – 1.jpg`
`| – – 2.jpg`
`| – – subfolder`

Is this possible? Thanks

**Comment by mattwidmann** [comment]
You can use the `transform` rule to strip the `subfolder` path component.
