### ISSUE TITLE
copy from outside the src directory

### ISSUE THREAD

**Issue by oupala** [mattwidmann/metalsmith-copy#17]
It appears that metalsmith-copy is unable to copy files from outside the `src` directory.

It would be great to add this feature as it would be handy to copy resources from the `node-module` (which is obviously outside the `src` directory).

**Comment by mattwidmann** [comment]
We don't have a handle on files outside of the source directory -- Metalsmith just provides us a list of files to transform. You could certainly add the node modules directory to your source as a symlink to work around this.

**Comment by oupala** [comment]
This is a good idea for linux, but probably won't work on windows. It is hard to make developments cross-platform compliant.

I'll have to find a solution.

**Comment by oupala** [comment]
metalsmith-assets seems to be able to copy files from outside src directory.
